using Domain_Service.Enums;
using System;
using System.ComponentModel.DataAnnotations;

namespace Domain_Service.Entities.PaymentAndPayout
{
    /// <summary>
    /// Represents a payment transaction made for a specific order.
    /// </summary>
    /// <remarks>
    /// This entity captures all essential details of a payment such as 
    /// the payment method, transaction reference, payment status, and timestamps.
    /// It is used for recording and tracking order payments in the system.
    /// </remarks>
    public class PaymentDetail
    {
        /// <summary>
        /// Primary key that uniquely identifies each payment record.
        /// </summary>
        [Key]
        public Guid PaymentDetailId { get; set; }

        /// <summary>
        /// Foreign key referencing the order for which this payment was made.
        /// </summary>
        public Guid OrderId { get; set; }

        /// <summary>
        /// The method used to complete the payment. 
        /// For example: Card, Cash, BankTransfer, Easypaisa, JazzCash, etc.
        /// </summary>
        public PaymentMethod PaymentMethod { get; set; }

        /// <summary>
        /// The transaction identifier generated by the payment gateway or system.
        /// </summary>
        /// <remarks>
        /// For cash payments, this may be generated internally.
        /// For online payments, it reflects the gateway transaction ID.
        /// </remarks>
        public string TransactionId { get; set; } = string.Empty;

        /// <summary>
        /// Indicates whether the payment is Pending, Successful, or Failed.
        /// </summary>
        /// <seealso cref="PaymentStatus"/>
        public PaymentStatus PaymentStatus { get; set; }

        /// <summary>
        /// The total amount paid by the user for the order.
        /// </summary>
        public double AmountPaid { get; set; }

        /// <summary>
        /// The timestamp indicating when this payment record was created.
        /// </summary>
        public DateTime CreatedAt { get; set; }
    }
}
