// <auto-generated />
using System;
using Infrastructure_Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure_Service.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260123121143_AddProvinceAndCityEntitiesWithSeeding")]
    partial class AddProvinceAndCityEntitiesWithSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain_Service.Entities.CartAndOrderModule.Cart", b =>
                {
                    b.Property<Guid>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CartId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Domain_Service.Entities.CartAndOrderModule.CartItem", b =>
                {
                    b.Property<Guid>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Domain_Service.Entities.CartAndOrderModule.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("OrderStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("PaymentStatus")
                        .HasColumnType("bit");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain_Service.Entities.CartAndOrderModule.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("PriceTotal")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Domain_Service.Entities.LocationModules.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000001"),
                            CityName = "Lahore",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000002"),
                            CityName = "Faisalabad",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000003"),
                            CityName = "Rawalpindi",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000004"),
                            CityName = "Gujranwala",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000005"),
                            CityName = "Multan",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000006"),
                            CityName = "Sargodha",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000007"),
                            CityName = "Sialkot",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000008"),
                            CityName = "Bahawalpur",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000009"),
                            CityName = "Jhang",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000010"),
                            CityName = "Sheikhupura",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000011"),
                            CityName = "Gujrat",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000012"),
                            CityName = "Sahiwal",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000013"),
                            CityName = "Rahim Yar Khan",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000014"),
                            CityName = "Kasur",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000015"),
                            CityName = "Okara",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000016"),
                            CityName = "Dera Ghazi Khan",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000017"),
                            CityName = "Chiniot",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000018"),
                            CityName = "Kamoke",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000019"),
                            CityName = "Hafizabad",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("aaaaaaaa-1111-0000-0000-000000000020"),
                            CityName = "Sadiqabad",
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000001"),
                            CityName = "Karachi",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000002"),
                            CityName = "Hyderabad",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000003"),
                            CityName = "Sukkur",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000004"),
                            CityName = "Larkana",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000005"),
                            CityName = "Nawabshah",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000006"),
                            CityName = "Mirpur Khas",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000007"),
                            CityName = "Jacobabad",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000008"),
                            CityName = "Shikarpur",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000009"),
                            CityName = "Khairpur",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000010"),
                            CityName = "Dadu",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000011"),
                            CityName = "Tando Adam",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000012"),
                            CityName = "Tando Allahyar",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000013"),
                            CityName = "Badin",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("bbbbbbbb-2222-0000-0000-000000000014"),
                            CityName = "Thatta",
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CityId = new Guid("cccccccc-3333-0000-0000-000000000001"),
                            CityName = "Peshawar",
                            ProvinceId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CityId = new Guid("cccccccc-3333-0000-0000-000000000002"),
                            CityName = "Mardan",
                            ProvinceId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CityId = new Guid("cccccccc-3333-0000-0000-000000000003"),
                            CityName = "Mingora",
                            ProvinceId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CityId = new Guid("cccccccc-3333-0000-0000-000000000004"),
                            CityName = "Kohat",
                            ProvinceId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CityId = new Guid("cccccccc-3333-0000-0000-000000000005"),
                            CityName = "Abbottabad",
                            ProvinceId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CityId = new Guid("cccccccc-3333-0000-0000-000000000006"),
                            CityName = "Mansehra",
                            ProvinceId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CityId = new Guid("cccccccc-3333-0000-0000-000000000007"),
                            CityName = "Nowshera",
                            ProvinceId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CityId = new Guid("cccccccc-3333-0000-0000-000000000008"),
                            CityName = "Dera Ismail Khan",
                            ProvinceId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CityId = new Guid("cccccccc-3333-0000-0000-000000000009"),
                            CityName = "Swabi",
                            ProvinceId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CityId = new Guid("cccccccc-3333-0000-0000-000000000010"),
                            CityName = "Charsadda",
                            ProvinceId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CityId = new Guid("cccccccc-3333-0000-0000-000000000011"),
                            CityName = "Bannu",
                            ProvinceId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CityId = new Guid("dddddddd-4444-0000-0000-000000000001"),
                            CityName = "Quetta",
                            ProvinceId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            CityId = new Guid("dddddddd-4444-0000-0000-000000000002"),
                            CityName = "Turbat",
                            ProvinceId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            CityId = new Guid("dddddddd-4444-0000-0000-000000000003"),
                            CityName = "Khuzdar",
                            ProvinceId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            CityId = new Guid("dddddddd-4444-0000-0000-000000000004"),
                            CityName = "Hub",
                            ProvinceId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            CityId = new Guid("dddddddd-4444-0000-0000-000000000005"),
                            CityName = "Chaman",
                            ProvinceId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            CityId = new Guid("dddddddd-4444-0000-0000-000000000006"),
                            CityName = "Gwadar",
                            ProvinceId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            CityId = new Guid("dddddddd-4444-0000-0000-000000000007"),
                            CityName = "Sibi",
                            ProvinceId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            CityId = new Guid("dddddddd-4444-0000-0000-000000000008"),
                            CityName = "Zhob",
                            ProvinceId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            CityId = new Guid("dddddddd-4444-0000-0000-000000000009"),
                            CityName = "Loralai",
                            ProvinceId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            CityId = new Guid("77777777-7777-0000-0000-000000000001"),
                            CityName = "Islamabad",
                            ProvinceId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            CityId = new Guid("66666666-6666-0000-0000-000000000001"),
                            CityName = "Muzaffarabad",
                            ProvinceId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            CityId = new Guid("66666666-6666-0000-0000-000000000002"),
                            CityName = "Mirpur",
                            ProvinceId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            CityId = new Guid("66666666-6666-0000-0000-000000000003"),
                            CityName = "Rawalakot",
                            ProvinceId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            CityId = new Guid("55555555-5555-0000-0000-000000000001"),
                            CityName = "Gilgit",
                            ProvinceId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            CityId = new Guid("55555555-5555-0000-0000-000000000002"),
                            CityName = "Skardu",
                            ProvinceId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            CityId = new Guid("55555555-5555-0000-0000-000000000003"),
                            CityName = "Hunza",
                            ProvinceId = new Guid("55555555-5555-5555-5555-555555555555")
                        });
                });

            modelBuilder.Entity("Domain_Service.Entities.LocationModules.Province", b =>
                {
                    b.Property<Guid>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProvinceName = "Punjab"
                        },
                        new
                        {
                            ProvinceId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProvinceName = "Sindh"
                        },
                        new
                        {
                            ProvinceId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProvinceName = "Khyber Pakhtunkhwa"
                        },
                        new
                        {
                            ProvinceId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProvinceName = "Balochistan"
                        },
                        new
                        {
                            ProvinceId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ProvinceName = "Gilgit-Baltistan"
                        },
                        new
                        {
                            ProvinceId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ProvinceName = "Azad Jammu & Kashmir"
                        },
                        new
                        {
                            ProvinceId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ProvinceName = "Islamabad Capital Territory"
                        });
                });

            modelBuilder.Entity("Domain_Service.Entities.PaymentAndPayout.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Domain_Service.Entities.PaymentAndPayout.PaymentDetail", b =>
                {
                    b.Property<Guid>("PaymentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AmountPaid")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentDetailId");

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("Domain_Service.Entities.ProductAndCategoryModule.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain_Service.Entities.ProductAndCategoryModule.ProductCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("4dba96a4-6fea-47df-af3a-e37cdbf0d2e7"),
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            CategoryId = new Guid("2f9abb81-f6ab-4507-8df5-f96a358edb51"),
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            CategoryId = new Guid("a1c3e5b2-3f4d-4c6e-8b2a-9f7e5d6c4b3a"),
                            CategoryName = "Books"
                        },
                        new
                        {
                            CategoryId = new Guid("b5e8f7c6-1d2a-4e3b-9c8d-7f6e5d4c3b2a"),
                            CategoryName = "Home & Kitchen"
                        },
                        new
                        {
                            CategoryId = new Guid("c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f"),
                            CategoryName = "Sports"
                        });
                });

            modelBuilder.Entity("Domain_Service.Entities.ProductAndCategoryModule.ProductImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ImageId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Domain_Service.Entities.SellerModule.Seller", b =>
                {
                    b.Property<Guid>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StoreDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SellerId");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Domain_Service.Entities.SellerModule.ShopDetail", b =>
                {
                    b.Property<Guid>("ShopDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShopDetailsId");

                    b.ToTable("ShopDetails");
                });

            modelBuilder.Entity("Domain_Service.Entities.SellerPaymentModule.SellerPayout", b =>
                {
                    b.Property<Guid>("SellerPayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AmountToPay")
                        .HasColumnType("float");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PayOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SellerPayoutId");

                    b.ToTable("SellerPayouts");
                });

            modelBuilder.Entity("Domain_Service.Entities.UserManagmentModule.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Domain_Service.Entities.UserManagmentModule.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreateAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain_Service.Entities.UserManagmentModule.UserCreadential", b =>
                {
                    b.Property<Guid>("CreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CreadId");

                    b.ToTable("UserCreadentials");
                });

            modelBuilder.Entity("Domain_Service.Entities.UserManagmentModule.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleName")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
