// <auto-generated />
using System;
using Infrastructure_Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure_Service.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260310205652_UserManagementEntities")]
    partial class UserManagementEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain_Service.Entities.CartAndOrderModule.Cart", b =>
                {
                    b.Property<Guid>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.HasKey("CartId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Domain_Service.Entities.CartAndOrderModule.CartItem", b =>
                {
                    b.Property<Guid>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("CartItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Domain_Service.Entities.CartAndOrderModule.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OrderStatus")
                        .HasColumnType("boolean");

                    b.Property<bool>("PaymentStatus")
                        .HasColumnType("boolean");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double precision");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain_Service.Entities.CartAndOrderModule.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("PriceTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderItemId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Domain_Service.Entities.LocationModules.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("11c32a0f-2c35-4bed-944a-9b4834423514"),
                            CityName = "Lahore",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("402b4b9f-894d-4fbb-9bab-27f034f814ad"),
                            CityName = "Faisalabad",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("32034cbb-d260-41c4-b39a-0455fb5b7bda"),
                            CityName = "Rawalpindi",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("d188f219-5336-45e1-bc0c-aaba9ce65d81"),
                            CityName = "Gujranwala",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("338d1125-136d-41d6-b171-f8e20555f901"),
                            CityName = "Multan",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("eb5c991a-102d-43e4-a740-8e8b6a962ede"),
                            CityName = "Sargodha",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("f89e5994-abeb-47ad-9599-f95689920b8a"),
                            CityName = "Sialkot",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("ae6a33f6-2f45-42cb-af2b-e6d181bbffea"),
                            CityName = "Bahawalpur",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("32588e15-db93-4f19-b6dd-65d80caf810b"),
                            CityName = "Jhang",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("6d5aee9a-339c-4cc5-b0bd-66c57ff1de9e"),
                            CityName = "Sheikhupura",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("eb050c4d-75cf-470f-b330-013be4eca2e6"),
                            CityName = "Gujrat",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("c6b54f01-ea91-44e6-b3fe-6cd85eb512e1"),
                            CityName = "Sahiwal",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("ff630a76-c931-4bc4-bce5-a605b05652e3"),
                            CityName = "Rahim Yar Khan",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("a4f8ca06-b1e8-428b-8a62-f2efc4b0bef2"),
                            CityName = "Kasur",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("4f322c4a-8818-4dbc-91ce-615d72271c90"),
                            CityName = "Okara",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("bde3519b-c2dd-46d3-9a0b-5b1bc9b73997"),
                            CityName = "Dera Ghazi Khan",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("b4d4551b-82fd-427c-9e5d-659eae19d0cf"),
                            CityName = "Chiniot",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("14ae1dbe-5538-48a4-8720-bf8627aaae62"),
                            CityName = "Kamoke",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("ee56c835-7c1a-4372-abf5-88a9c2799804"),
                            CityName = "Hafizabad",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("f76b553e-4b0b-46e5-8749-710a5102c81a"),
                            CityName = "Sadiqabad",
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21")
                        },
                        new
                        {
                            CityId = new Guid("91073ac3-82ff-431c-90a3-71eef030f0b7"),
                            CityName = "Karachi",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("bb78a831-6e4f-46f4-b9dd-28026b2a1a3a"),
                            CityName = "Hyderabad",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("997f5b82-6b94-42d7-992e-f4bd0da6a2a0"),
                            CityName = "Sukkur",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("ad9359d0-0c4e-4d24-987e-e3c773823d2a"),
                            CityName = "Larkana",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("8ae33231-8054-4385-9293-da05b23c0f8a"),
                            CityName = "Nawabshah",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("4592eac9-44b4-42a3-aa84-797802243054"),
                            CityName = "Mirpur Khas",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("569eb43d-d99f-442c-851e-f8afcc00b8ac"),
                            CityName = "Jacobabad",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("aa9c8403-7d5e-48ee-9779-f995ee877ff8"),
                            CityName = "Shikarpur",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("e15b5409-d8ad-4ddb-8282-4afb191af1b7"),
                            CityName = "Khairpur",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("7e3c34d3-a3f4-4af4-a64b-b232a35378cb"),
                            CityName = "Dadu",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("462a5a3b-5663-48e1-a171-2bfd5e5165a6"),
                            CityName = "Tando Adam",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("18f837b7-8b36-4bfb-88dd-b933e153e145"),
                            CityName = "Tando Allahyar",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("9f203761-9a8a-4efa-844a-dc96e37940dc"),
                            CityName = "Badin",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("ff74b59c-960e-4e39-84b2-472897052201"),
                            CityName = "Thatta",
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2")
                        },
                        new
                        {
                            CityId = new Guid("e567ffc2-01a2-4bdc-8f2a-4dc594ae0e0b"),
                            CityName = "Peshawar",
                            ProvinceId = new Guid("2f3545e6-6ded-49f8-b597-c2119122607c")
                        },
                        new
                        {
                            CityId = new Guid("9948c980-bbcf-49a3-a601-a3f36011af44"),
                            CityName = "Mardan",
                            ProvinceId = new Guid("2f3545e6-6ded-49f8-b597-c2119122607c")
                        },
                        new
                        {
                            CityId = new Guid("d0cbadcf-a7cf-44ea-90eb-d30a00448bfc"),
                            CityName = "Mingora",
                            ProvinceId = new Guid("2f3545e6-6ded-49f8-b597-c2119122607c")
                        },
                        new
                        {
                            CityId = new Guid("2a8b9931-a32a-450f-8546-5a1dc0760195"),
                            CityName = "Kohat",
                            ProvinceId = new Guid("2f3545e6-6ded-49f8-b597-c2119122607c")
                        },
                        new
                        {
                            CityId = new Guid("4d450f55-b872-419e-86ad-67b9529a55ee"),
                            CityName = "Abbottabad",
                            ProvinceId = new Guid("2f3545e6-6ded-49f8-b597-c2119122607c")
                        },
                        new
                        {
                            CityId = new Guid("92b1df1a-a012-4236-95cc-fb8e1fcbb36d"),
                            CityName = "Mansehra",
                            ProvinceId = new Guid("2f3545e6-6ded-49f8-b597-c2119122607c")
                        },
                        new
                        {
                            CityId = new Guid("1dc110e3-7c9a-402a-b11a-5aef0ef63696"),
                            CityName = "Nowshera",
                            ProvinceId = new Guid("2f3545e6-6ded-49f8-b597-c2119122607c")
                        },
                        new
                        {
                            CityId = new Guid("91385f60-8e52-413a-b16e-cca98adeeb7d"),
                            CityName = "Dera Ismail Khan",
                            ProvinceId = new Guid("2f3545e6-6ded-49f8-b597-c2119122607c")
                        },
                        new
                        {
                            CityId = new Guid("f121ad28-472d-4018-9a4a-92f871f91f08"),
                            CityName = "Swabi",
                            ProvinceId = new Guid("2f3545e6-6ded-49f8-b597-c2119122607c")
                        },
                        new
                        {
                            CityId = new Guid("626922d0-9b48-42c6-a00a-16253850260e"),
                            CityName = "Charsadda",
                            ProvinceId = new Guid("2f3545e6-6ded-49f8-b597-c2119122607c")
                        },
                        new
                        {
                            CityId = new Guid("9fbc2de0-8290-49bf-92ce-d0769d8c6753"),
                            CityName = "Bannu",
                            ProvinceId = new Guid("2f3545e6-6ded-49f8-b597-c2119122607c")
                        },
                        new
                        {
                            CityId = new Guid("a66671cf-3852-4e75-8433-6d84a13c8f1d"),
                            CityName = "Quetta",
                            ProvinceId = new Guid("e4c46d9c-da92-43df-a374-b3b2b02da7b7")
                        },
                        new
                        {
                            CityId = new Guid("336eb174-945c-4d13-b6d7-0dc8a7f8c428"),
                            CityName = "Turbat",
                            ProvinceId = new Guid("e4c46d9c-da92-43df-a374-b3b2b02da7b7")
                        },
                        new
                        {
                            CityId = new Guid("e8a034ea-de40-418d-b43c-87ed7b966c54"),
                            CityName = "Khuzdar",
                            ProvinceId = new Guid("e4c46d9c-da92-43df-a374-b3b2b02da7b7")
                        },
                        new
                        {
                            CityId = new Guid("819b29d3-9cf7-4783-99d3-9d12f525f266"),
                            CityName = "Hub",
                            ProvinceId = new Guid("e4c46d9c-da92-43df-a374-b3b2b02da7b7")
                        },
                        new
                        {
                            CityId = new Guid("e9523429-a45e-400e-aec1-ba3873a9a81a"),
                            CityName = "Chaman",
                            ProvinceId = new Guid("e4c46d9c-da92-43df-a374-b3b2b02da7b7")
                        },
                        new
                        {
                            CityId = new Guid("414d1212-38ad-40b3-a2c1-cf2d78e84102"),
                            CityName = "Gwadar",
                            ProvinceId = new Guid("e4c46d9c-da92-43df-a374-b3b2b02da7b7")
                        },
                        new
                        {
                            CityId = new Guid("95aa8286-2a60-4697-a032-1823b5341aed"),
                            CityName = "Sibi",
                            ProvinceId = new Guid("e4c46d9c-da92-43df-a374-b3b2b02da7b7")
                        },
                        new
                        {
                            CityId = new Guid("fe1b9b1e-183e-4bf6-8844-4c4682fc79e3"),
                            CityName = "Zhob",
                            ProvinceId = new Guid("e4c46d9c-da92-43df-a374-b3b2b02da7b7")
                        },
                        new
                        {
                            CityId = new Guid("7ef47141-9ffa-4996-a6e7-390572e80cc9"),
                            CityName = "Loralai",
                            ProvinceId = new Guid("e4c46d9c-da92-43df-a374-b3b2b02da7b7")
                        },
                        new
                        {
                            CityId = new Guid("5aed5695-35db-4615-8b4d-1d6ac392d54d"),
                            CityName = "Islamabad",
                            ProvinceId = new Guid("b00ebfe6-ff2b-474c-a2a5-90a3ac8077cf")
                        },
                        new
                        {
                            CityId = new Guid("ba78eef6-fb33-4e1d-aa5e-dd662f5b2971"),
                            CityName = "Muzaffarabad",
                            ProvinceId = new Guid("2652700e-a4e6-4d85-97de-28a104caabde")
                        },
                        new
                        {
                            CityId = new Guid("298c5cf0-ad10-4dca-8c57-49a8cd68dfa4"),
                            CityName = "Mirpur",
                            ProvinceId = new Guid("2652700e-a4e6-4d85-97de-28a104caabde")
                        },
                        new
                        {
                            CityId = new Guid("63e715cb-7e89-40f4-a717-e1756933abe3"),
                            CityName = "Rawalakot",
                            ProvinceId = new Guid("2652700e-a4e6-4d85-97de-28a104caabde")
                        },
                        new
                        {
                            CityId = new Guid("4d063868-59a2-4728-8b19-25bf97c96b6a"),
                            CityName = "Gilgit",
                            ProvinceId = new Guid("0ebeb3fe-742c-4c32-afb6-ee706b26fcd9")
                        },
                        new
                        {
                            CityId = new Guid("5384e9bd-b1a1-48fb-a762-dec319f95b9d"),
                            CityName = "Skardu",
                            ProvinceId = new Guid("0ebeb3fe-742c-4c32-afb6-ee706b26fcd9")
                        },
                        new
                        {
                            CityId = new Guid("4b79eb8e-b3d6-4d5e-b6b6-30960bfd1705"),
                            CityName = "Hunza",
                            ProvinceId = new Guid("0ebeb3fe-742c-4c32-afb6-ee706b26fcd9")
                        });
                });

            modelBuilder.Entity("Domain_Service.Entities.LocationModules.Province", b =>
                {
                    b.Property<Guid>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProvinceId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = new Guid("91755a1c-9c22-46d3-aed6-d40a3cce1c21"),
                            ProvinceName = "Punjab"
                        },
                        new
                        {
                            ProvinceId = new Guid("047fed8b-d44a-428b-9e16-7777972e01f2"),
                            ProvinceName = "Sindh"
                        },
                        new
                        {
                            ProvinceId = new Guid("2f3545e6-6ded-49f8-b597-c2119122607c"),
                            ProvinceName = "Khyber Pakhtunkhwa"
                        },
                        new
                        {
                            ProvinceId = new Guid("e4c46d9c-da92-43df-a374-b3b2b02da7b7"),
                            ProvinceName = "Balochistan"
                        },
                        new
                        {
                            ProvinceId = new Guid("0ebeb3fe-742c-4c32-afb6-ee706b26fcd9"),
                            ProvinceName = "Gilgit-Baltistan"
                        },
                        new
                        {
                            ProvinceId = new Guid("2652700e-a4e6-4d85-97de-28a104caabde"),
                            ProvinceName = "Azad Jammu & Kashmir"
                        },
                        new
                        {
                            ProvinceId = new Guid("b00ebfe6-ff2b-474c-a2a5-90a3ac8077cf"),
                            ProvinceName = "Islamabad Capital Territory"
                        });
                });

            modelBuilder.Entity("Domain_Service.Entities.PaymentAndPayout.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Domain_Service.Entities.PaymentAndPayout.PaymentDetail", b =>
                {
                    b.Property<Guid>("PaymentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AmountPaid")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentDetailId");

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("Domain_Service.Entities.ProductAndCategoryModule.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Discount")
                        .HasColumnType("double precision");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSold")
                        .HasColumnType("integer");

                    b.Property<int>("TotalViews")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain_Service.Entities.ProductAndCategoryModule.ProductCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("4dba96a4-6fea-47df-af3a-e37cdbf0d2e7"),
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            CategoryId = new Guid("2f9abb81-f6ab-4507-8df5-f96a358edb51"),
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            CategoryId = new Guid("a1c3e5b2-3f4d-4c6e-8b2a-9f7e5d6c4b3a"),
                            CategoryName = "Books"
                        },
                        new
                        {
                            CategoryId = new Guid("b5e8f7c6-1d2a-4e3b-9c8d-7f6e5d4c3b2a"),
                            CategoryName = "Home & Kitchen"
                        },
                        new
                        {
                            CategoryId = new Guid("c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f"),
                            CategoryName = "Sports"
                        });
                });

            modelBuilder.Entity("Domain_Service.Entities.ProductAndCategoryModule.ProductImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CloudPublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ImageId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Domain_Service.Entities.ProductManagmentModule.ProductReview", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("ReviewId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("Domain_Service.Entities.ProductManagmentModule.ProductView", b =>
                {
                    b.Property<Guid>("ProductViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductViewId");

                    b.ToTable("ProductViews");
                });

            modelBuilder.Entity("Domain_Service.Entities.ProductManagmentModule.WishList", b =>
                {
                    b.Property<Guid>("WishListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CrestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("WishListId");

                    b.ToTable("WishLists");
                });

            modelBuilder.Entity("Domain_Service.Entities.ProductManagmentModule.WishListItem", b =>
                {
                    b.Property<Guid>("WishListItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WishListId")
                        .HasColumnType("uuid");

                    b.HasKey("WishListItemId");

                    b.ToTable("WishListItems");
                });

            modelBuilder.Entity("Domain_Service.Entities.SellerModule.Seller", b =>
                {
                    b.Property<Guid>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoreDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SellerId");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Domain_Service.Entities.SellerModule.ShopDetail", b =>
                {
                    b.Property<Guid>("ShopDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShopDetailsId");

                    b.ToTable("ShopDetails");

                    b.HasData(
                        new
                        {
                            ShopDetailsId = new Guid("737eaf82-f95c-4fd2-b07b-48b73b34fa3e"),
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("bebdcdbb-4f49-43ca-a386-8557122342bf"),
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("702d36c2-f1c3-4f15-a2ac-d89b219b2c66"),
                            CategoryName = "Books"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("7195ec03-cd19-4198-80ee-1f3a0219b3c8"),
                            CategoryName = "Home & Kitchen"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("7ef2ec4a-7bba-4041-84c8-88ac50441fe5"),
                            CategoryName = "Sports"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("1894c8ce-b6e3-41f7-90e5-bb7ed72d58b9"),
                            CategoryName = "Mobiles & Tablets"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("044808fa-b50d-4158-87f1-1c366ade2fc4"),
                            CategoryName = "Laptops & Computers"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("1b43faa3-43b9-4b5c-b00a-df27f60e3548"),
                            CategoryName = "Beauty & Personal Care"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("6f96c2f1-3c56-41fe-ad1e-0cf9ae562b8a"),
                            CategoryName = "Toys & Games"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("0797ea35-90ed-4cd2-8bfa-418b65fec051"),
                            CategoryName = "Health & Household"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("e38e2e44-d181-424e-adbd-90f4d01bab6f"),
                            CategoryName = "Automotive"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("c86da114-d7b8-48ec-870c-16e2ab0306ef"),
                            CategoryName = "Groceries & Pet Supplies"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("400df0e2-af62-4f81-861c-7d27e1ad5dbe"),
                            CategoryName = "Tools & Improvement"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("3218c802-d573-461a-a65b-9a5d0df6123e"),
                            CategoryName = "Watches & Jewelry"
                        },
                        new
                        {
                            ShopDetailsId = new Guid("ad7e8ada-c088-470b-854d-e7358017a683"),
                            CategoryName = "Video Games"
                        });
                });

            modelBuilder.Entity("Domain_Service.Entities.SellerPaymentModule.SellerPayout", b =>
                {
                    b.Property<Guid>("SellerPayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AmountToPay")
                        .HasColumnType("double precision");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PayOutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.HasKey("SellerPayoutId");

                    b.ToTable("SellerPayouts");
                });

            modelBuilder.Entity("Domain_Service.Entities.UserManagmentModule.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CloudPublicId")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Domain_Service.Entities.UserManagmentModule.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CloudPublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("CreateAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain_Service.Entities.UserManagmentModule.UserCreadential", b =>
                {
                    b.Property<Guid>("CreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OTPExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CreadId");

                    b.ToTable("UserCreadentials");
                });

            modelBuilder.Entity("Domain_Service.Entities.UserManagmentModule.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Domain_Service.Entities.UserManagmentModule.UserSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId");

                    b.ToTable("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
